import fs from "node:fs";
import assert from "node:assert/strict";

const html=fs.readFileSync("index.html","utf8");
const oldWebLink="https://ig.me/m/patocreando?ref=w61000387";
const count=(str,text)=>str.split(text).length-1;
const match=(needle)=>assert.ok(html.includes(needle),"Missing: "+needle);
const sectionIds=[...html.matchAll(/<section\b[^>]*\bid="([^"]+)"/g)].map(x=>x[1]);
assert.deepEqual(sectionIds,["inicio","solucion","capacidades","planes","proceso","faq"],"Original storytelling chapters preserved");
assert.equal(count(html,'<h1>'),1,"One primary H1");
assert.equal(count(html,'class="web-conversion-header"'),1,"Exactly one persistent conversion header");
assert.equal(count(html,'id="web-conversion-critical"'),1,"Critical nav and CTAs CSS embedded atomically");
assert.ok(html.indexOf('id="web-conversion-critical"')<html.indexOf('</head>'),"Conversion CSS in head");
assert.equal(count(html,'class="home-return"'),0,"No conflicting floating home-return link");
assert.equal(count(html,'class="web-conversion-primary"'),0,"Only registered CTAs");
match('href="https://patocreando.github.io/inicio/"');
match('class="web-conversion-brand" href="#inicio"');
match('class="web-conversion-contact" href="'+oldWebLink+'"');
match('class="hero-conversion-primary" href="'+oldWebLink+'"');
match('class="hero-conversion-secondary" href="#planes"');
match('class="hero-conversion-note"');
match('Desde ARS 30.000 · Pago único');
match('id="planes"');
match('id="faq"');
match('id="main-content"');
match('href="#main-content"');
match('<video id="masterFilmVideo" muted playsinline preload="metadata">');
assert.ok(count(html,oldWebLink)>=5,"All previous Web Manychat links remain and new early CTAs use the same ref");
const amounts=[["Web Express","ARS 30.000"],["Web Pro","ARS 75.000"],["Web Premium","ARS 150.000"]];
for(const [name,price] of amounts) {match(name);assert.equal(count(html,price)>=1,true,"Price preserved "+price);}
for(const term of ["1 ajuste","2 ajustes","3 ajustes","Diseño personalizado","SEO básico","Dominio propio","Página avanzada o multipágina"])match(term);
match("Alcance, plazos y condiciones de pago se acuerdan antes de empezar.");
match('aria-label="Navegación principal"');
match('meta name="description" content="Diseño de landing pages');
assert.equal(count(html,'class="plan-x '),3,"Three original plans still present");
for(const file of ["styles.css","hero-v3.css","experience.css","script.js","capabilities.js","plans.js","process.js","polish.js","film.js","kinetic.js","close-zone.js"])assert.ok(fs.existsSync(file),"Original asset missing "+file);
const css=html.slice(html.indexOf('<style id="web-conversion-critical">'),html.indexOf('</style>',html.indexOf('<style id="web-conversion-critical">')));
for(const style of [".web-conversion-nav",".hero-conversion-actions","#solucion,#capacidades,#planes,#proceso,#faq","@media(max-width:720px)"])assert.ok(css.includes(style),"Responsive style missing "+style);
const anchors=[...html.matchAll(/<a\b[^>]*href="#([^"]+)"/g)].map(x=>x[1]);
const ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]));
for(const anchor of anchors)assert.ok(ids.has(anchor),"Broken local anchor #"+anchor);
console.log("Web conversion static smoke OK: pricing, Manychat, chapter structure, hero CTAs and responsive CSS.");